version: '3.8'

services :

    gateway:
        image: devopsfaith/krakend:1.2.0
        volumes:
            - ./gateway:/etc/krakend
        ports:
            - 8080:8080


    task-svc:
        build: ./task-svc/.
        command: ./task-svc
        restart: on-failure
        ports:
            - 8003:8080
        

    # db: 
    #     restart: always
    #     image: postgres:12.0-alpine
    #     ports: 
    #         - 5433:5432
    #     volumes:
    #         - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    #         - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    #     environment:
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=qwerty